name: get-meldefonds
on:
  schedule:
    - cron: '0 7 * * 6'
  workflow_dispatch:
jobs: 
  get-meldefonds:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
          architecture: 'x64'
      - name: Download and install Python dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Download tax reporting fund data from OeKB
        run: python meldefonds.py
      - name: Commit latest OeKB data
        run: |
          git config --global user.name "algebrazebra"
          git config --global user.email "algebrazebra@users.noreply.github.com"
          git add meldefonds.csv meldefonds.json
          git commit -m "Meldefonds (`date +'%Y-%m-%d %H:%M:%S'`)"
          git push
